---
# Following install guides:
# https://spacelift.io/blog/ansible-kubernetes
# https://hbayraktar.medium.com/how-to-install-kubernetes-cluster-on-ubuntu-22-04-step-by-step-guide-7dbf7e8f5f99

- name: Setup linux environment
  tags: linux
  ansible.builtin.include_tasks: ./setup_linux.yml

- name: Configure apt repos
  tags: apt
  ansible.builtin.include_tasks: ./configure_apt.yml

- name: Install containerd
  tags: containerd
  ansible.builtin.include_tasks: ./install_containerd.yml

- name: Install kubelet
  tags: kubelet
  ansible.builtin.include_tasks: ./install_kubelet.yml
