---
- name: Setup linux environment
  tags: linux
  block:
    - name: Update apt
      ansible.builtin.apt:
        update_cache: true

    - name: Disable swap
      ansible.builtin.command: |
        swapoff -a
      changed_when: false

    - name: Disable/Comment out SWAP in fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: ^([^#].*?\sswap\s+sw\s+.*)$
        replace: "# \\1"

- name: Configure kernel modules
  vars:
    config_path: /etc/modules-load.d/containerd.conf
  block:
    - name: Create containerd.conf
      ansible.builtin.copy:
        content: ""
        dest: "{{ config_path }}"
        force: false
        owner: root
        group: root
        mode: "0644"

    - name: Configure containerd.conf
      ansible.builtin.blockinfile:
        path: "{{ config_path }}"
        block: |
          overlay
          br_netfilter

- name: Configure k8s sysctl parameters
  vars:
    config_path: /etc/sysctl.d/99-kubernetes.conf
  block:
    - name: Create sysctl conf
      ansible.builtin.copy:
        content: ""
        dest: "{{ config_path }}"
        force: false
        owner: root
        group: root
        mode: "0644"

    - name: Configure sysctl conf
      ansible.builtin.lineinfile:
        path: "{{ config_path }}"
        line: "{{ item }}"
      with_items:
        - net.bridge.bridge-nf-call-iptables  = 1
        - net.ipv4.ip_forward                 = 1
        - net.bridge.bridge-nf-call-ip6tables = 1

    - name: Apply sysctl parameters
      ansible.builtin.command: |
        sysctl --system
      changed_when: false
